spring.application.name=mym_dentist_commerce
server.port = 8080

#Conection database

# Database connection settings
spring.datasource.url=${DB_PATH}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Spring security

aws.s3.bucket.name=${AWS_BUCKET_NAME:kjasdk}

aws.accessKeyId=${PUBLIC_KEY:}
aws.secretKey=${SECRET_KEY:}
aws.sessionToken=${TOKEN_KEY:}

# CORS Config
spring.cors.origins.test=${LOCAL_PATH:http://localhost:5173}
spring.cors.origins.cloudfront=${CLOUDFRONT_PATH:cddd}
spring.cors.origins.s3Bucket=${S3_BUCKET_PAGE:asdasd}